### ISSUE TITLE
Error in sleuth_live using gene_mode=TRUE

### ISSUE THREAD

**Issue by lmigueel** [pachterlab/sleuth#190] opened 2018-06-27 15:22 UTC
Hello,

I got an error  when I used the argument _gene_mode=TRUE_ on _sleuth_live_. The first part of the figure shows a bug in gene box. When I tryed to find one gene, I got the error _"Error: could not find function "gene_from_gene"_ (second part of the figure). How I can solve this? Anyone can help me?

![erro-sleuth_live](https://user-images.githubusercontent.com/37070949/41983361-40b865c0-7a04-11e8-9f8d-de14251fcdb2.png)

Thanks.

**Comment by warrenmcg** [comment] 2018-06-27 16:15
Hi @lmigueel, thanks for pointing this out! This was a function that was supposed to be present that got lost in the shuffle of merging branches, and we didn't catch it during testing. I'm doing an emergency patch now.

**Comment by warrenmcg** [comment] 2018-06-28 14:17
Hi @lmigueel, the issue is fixed. If you reinstall sleuth using devtools, the newest master commit should be installed, with the method restored.

```
devtools::install_github('pachterlab/sleuth')
```

**Comment by lmigueel** [comment] 2018-06-28 21:18
Hi @warrenmcg,

Thanks for your reply. I reinstalled sleuth but I got one different error. Look the figure. 
It's seems that sleuth can not find the gene agregated column. The column _ens_gene_ is on my _transcript2gene_ file.

![erro-leuth2](https://user-images.githubusercontent.com/37070949/42060978-feca495c-7afe-11e8-99d0-3911bff47778.png)

Regards,

**Comment by warrenmcg** [comment] 2018-06-28 21:42
Hi @lmigueel, sorry you are continuing to have problems and thanks for bringing this back to our attention. I've identified the issue, and hopefully get a patch out soon.

**Comment by warrenmcg** [comment] 2018-06-28 21:50
Hi @lmigueel, I've pushed a patch. If you want to immediately work with it before it gets folded into master, you can do so by doing the following:
```
devtools::github_install('warrenmcg/sleuth', ref = 'patch_g2g')
```
This is exactly the same version except with the patched included. Let me know if you experience any further difficulties. We'll close this issue when the patch gets folded into master

**Comment by warrenmcg** [comment] 2018-06-29 00:40
@lmigueel, did you use the exact line that I gave you? This patch is not on master yet, so doing the usual install_github will result in no change and the same error. My patch works on my end, so it should work on yours.

**Comment by lmigueel** [comment] 2018-07-02 21:37
Hello @warrenmcg ,

I would like to thank you. The bug is fixed. 

Regards,

**Closed** 2019-12-17 21:53 UTC
