### ISSUE TITLE
show_all = TRUE?

### ISSUE THREAD

**Issue by sklasfeld** [pachterlab/sleuth#133] opened 2017-08-23 18:17 UTC
Hello,
  I am trying to compare the differential expression of genes, and I would like to include genes that have 0 expression in one condition and expression in a different condition. These get filtered out in 'sleuth_prep' since they have low counts in multiple samples and another discussion says these low counts negatively affect the scaling in sleuth. Therefore, I would like to show_all in sleuth_results at the end even when they are not used for scaling. However, when I start the analysis I have '19568' genes from kallisto (i merged the kallisto transcripts with `tximport` just to see) but in the end of sleuth it only reports `11704` genes. I used the parameter "show_all=TRUE" in sleuth_results.

**Comment by warrenmcg** [comment] 2017-09-20 13:32
The sleuth_results table should give you all 19568 genes, but it will give you `NA` for all of the genes that were filtered out, since they are not run through the regression model. Is that what you're seeing, or are you literally only seeing 11704 genes when you have 19568 genes in the annotations?

A suggestion is that you can change the filter to fit your experimental context. The default filter used by `sleuth` is called `basic_filter`. Here is the code for that:

```
basic_filter <- function (row, min_reads = 5, min_prop = 0.47) 
{
    mean(row >= min_reads) >= min_prop
}
```

It filters out all genes that do not have at least 5 estimated counts in at least 47% of the samples (which usually means ½). You can create your own filter by tweaking the parameters yourself:

```
skalsfeld_filter <- function(row, min_reads = [WHATEVER], min_prop = [Number between 0-1])
{
    mean(row >= min_reads) >= min_prop
}
```
Then when you run `sleuth_prep`, use the `filter_fun` argument to specify your own filter like this:
```
sleuth_object <- sleuth_prep(sample_to_covariates, target_mapping = t2g, filter_fun = skalsfeld_filter, ...[ETC])
```

Hope this helps!

**Comment by warrenmcg** [comment] 2017-10-23 18:13
pinging @sklasfeld, could you let me know if my suggestion from before helped with your problem, or if there is a bug that we need to follow-up? Thanks!

**Comment by sklasfeld** [comment] 2017-10-23 19:35
This helped! Thank you so much!

**Comment by warrenmcg** [comment] 2017-10-23 19:47
Glad to hear it! Ok, I'll close this issue then.

**Closed by warrenmcg** 2017-10-23 19:47 UTC
