### ISSUE TITLE
beta values do not appear in Wald test results when the analysis is performed with gene level aggregation

### ISSUE THREAD

**Issue by kalyanuw** [pachterlab/sleuth#183] opened 2018-06-12 20:42 UTC
The overall issue is that Wald test results are missing beta values when the analysis of Kallisto output is conducted with gene level aggregation. The issue does not occur not with transcript level analysis. How do I retrieve beta values with a Wald test under gene level aggregation?
I ran the following scripts in R3.5/RStudio, with a current installation of Sleuth, biomaRt, and rhdf5. 

When I run a Wald test using the following script, results_table_wt has 11 variables: target_id, pval, qval, b, se_b, mean_obs, var_obs, tech_var, sigma_sq, smooth_sigma_sq, final_sigma_sq

library(sleuth)
base_dir <- "library(sleuth)
base_dir <- "C:/Users/xyz/Documents/MATLAB/Liver_GENT"
sample_id <- dir(file.path(base_dir,"rat_GENTveh"))
kal_dirs <- sapply(sample_id, function(id) file.path(base_dir, "rat_GENTveh", id))
s2c <- read.table(file.path(base_dir, "all_samples_control_new.info"), header = TRUE, stringsAsFactors=FALSE)
s2c <- dplyr::select(s2c, sample = run_accession, condition)
s2c <- dplyr::mutate(s2c, path = kal_dirs)
so <- sleuth_prep(s2c, ~ condition)
so <- sleuth_fit(so)
so <- sleuth_wt(so,which_beta = 'conditionVehicle7',which_model = 'full')
results_table_wt <- sleuth_results(so,'conditionVehicle7',test_type='wt')"
sample_id <- dir(file.path(base_dir,"rat_GENTveh"))
kal_dirs <- sapply(sample_id, function(id) file.path(base_dir, "rat_GENTveh", id))
s2c <- read.table(file.path(base_dir, "all_samples_control_new.info"), header = TRUE, stringsAsFactors=FALSE)
s2c <- dplyr::select(s2c, sample = run_accession, condition)
s2c <- dplyr::mutate(s2c, path = kal_dirs)
so <- sleuth_prep(s2c, ~ condition)
so <- sleuth_fit(so)
so <- sleuth_wt(so,which_beta = 'conditionVehicle7',which_model = 'full')
results_table_wt <- sleuth_results(so,'conditionVehicle7',test_type='wt')

However, when I aggregate at the gene level by running the following script and conduct a Wald test, results_table_wt has only 6 variables: target_id, ext_gene, num_aggregated_transcripts, sum_mean_obs_counts, pval, qval

library(sleuth)
base_dir <- "C:/Users/xyz/Documents/MATLAB/Liver_GENT"
sample_id <- dir(file.path(base_dir,"rat_GENTveh"))
kal_dirs <- sapply(sample_id, function(id) file.path(base_dir, "rat_GENTveh", id))
s2c <- read.table(file.path(base_dir, "all_samples_control_new.info"), header = TRUE, stringsAsFactors=FALSE)
s2c <- dplyr::select(s2c, sample = run_accession, condition)
s2c <- dplyr::mutate(s2c, path = kal_dirs)

library("biomaRt")
ensembl=useMart(biomart="ENSEMBL_MART_ENSEMBL", host="uswest.ensembl.org")
listDatasets(ensembl)
mart <- biomaRt::useMart(biomart="ENSEMBL_MART_ENSEMBL",dataset="rnorvegicus_gene_ensembl",host='uswest.ensembl.org')
t2g = biomaRt::getBM(attributes = c("ensembl_transcript_id","ensembl_gene_id","external_gene_name"),mart = mart)
t2g<-dplyr::rename(t2g,target_id=ensembl_transcript_id,ens_gene = ensembl_gene_id,ext_gene = external_gene_name)

so <- sleuth_prep(s2c, ~condition, target_mapping = t2g,aggregation_column = 'ens_gene', extra_bootstrap_summary = TRUE)
so <- sleuth_fit(so)

so <- sleuth_wt(so,which_beta = 'conditionVehicle7',which_model = 'full')
results_table_wt <- sleuth_results(so,'conditionVehicle7',test_type='wt')

**Comment by warrenmcg** [comment] 2018-06-12 23:20
Hi @kalyanuw, 

Thanks for using the new version of the tool!

What you're describing is expected behavior, and not a bug or a problem. The new p-value aggregation method focuses the aggregation on the p-values generated, whether by the Wald test (`sleuth_wt`) or the Likelihood Ratio test (`sleuth_lrt`). Because the transcripts could be changing up or down, there is no longer a coherent sense in which you can report a "beta" at the gene-level using this approach.

If you still wish to get betas at the gene-level, this must be done using the old counts aggregation method. To do this you simply need to run sleuth_prep with `gene_mode = TRUE` like so:
```
so <- sleuth_prep(s2c, ~condition, target_mapping = t2g, aggregation_column = 'ens_gene', 
                  extra_bootstrap_summary = TRUE,
                  gene_mode = TRUE) ## Here is the extra option
so <- sleuth_fit(so)
so <- sleuth_wt(so, which_beta = 'conditionVehicle7', which_model = 'full')
results_table_wt <- sleuth_results(so, 'conditionVehicle7', test_type='wt')
```

If you wish to look at the betas of the TPM values (instead of counts), you must set `read_bootstrap_tpm = TRUE` like this:
```
so <- sleuth_prep(s2c, ~condition, target_mapping = t2g, aggregation_column = 'ens_gene',
                  extra_bootstrap_summary = TRUE,
                  read_bootstrap_tpm = TRUE,  ## Here is the extra option
                  gene_mode = TRUE)
## You must set which_var to "obs_tpm" in sleuth_fit to model TPMs
so <- sleuth_fit(so, which_var = "obs_tpm") 
so <- sleuth_wt(so, which_beta = 'conditionVehicle7', which_model = 'full')
results_table_wt <- sleuth_results(so, 'conditionVehicle7', test_type='wt')
```

Since this is expected behavior, I'm going to close this issue. However, if you follow these instructions and you still don't get beta values, feel free to reopen this issue and report back. If you have usage questions, please use the [google forum](https://groups.google.com/forum/#!forum/kallisto-sleuth-users).

**Closed by warrenmcg** 2018-06-12 23:20 UTC
