### ISSUE TITLE
Where is the b value in sleuth_results table?

### ISSUE THREAD

**Issue by Rhinogradentia** [pachterlab/sleuth#127] opened 2017-07-12 17:30 UTC
Hi,

I think I've done something wrong maybe. I can't find the b-value in the results table anymore.
Following columns are in my table:
target_id 
test_stat         
pval         
qval        
rss    
sigma_sq     
tech_var 
mean_obs     
var_obs 
sigma_sq_pmax 
smooth_sigma_sq 
final_sigma_sq 
degrees_free

My call looks like this:
so <- sleuth_prep(s2c, ~ condition, target_mapping = t2g)
so <- sleuth_fit(so, ~1, 'reduced')
so <- sleuth_lrt(so, 'reduced', 'full')
sleuth_table <- sleuth_results(so, 'reduced:full', 'lrt', show_all = TRUE)

I'm running the most recent version of sleuth.

Please help!

Thanks
Bye
Nadine

**Comment by warrenmcg** [comment] 2017-07-12 19:17
Hi Nadine (@Rhinogradentia)!

First of all, great to see you using the tool and it's good for you to reach out to receive help.

This thankfully can be easily addressed, and has been addressed before. You used the Likelihood Ratio Test (LRT), called by `sleuth_lrt`. You only get a `b` (= 'beta') value from the Wald test, called by using `sleuth_wt`.

The LRT compares to models to see which is a better fit to the data, which is calculated based on the "log-likelihood" of the data given the model. As the name suggests, the LRT takes the ratio of the log-likelihoods between the two models. This ratio can itself be modeled as a Chi-squared statistic with the degrees of freedom as the difference of degrees of freedom between the two models. The p-value reported is the p-value on this Chi-Squared distribution. The `rss` value you see is the residual sum of squares, which basically means the "unexplained variance" after using the more complicated to model the data.

If you want b values, you have to run `sleuth_wt`. If you have more than two conditions, then you need to specify the `which_beta` argument for `sleuth_wt`. You can find which ones to use by calling `models(so)`.

If you have further questions while doing your analysis, I would recommend first reading the documentation provided on the [sleuth website](http://pachterlab.github.io/sleuth/) and by using the `?` feature of R (to learn more about `sleuth_wt`, type `?sleuth_wt` in R). If you still have questions, search the archived posts on the [google group](https://groups.google.com/forum/#!forum/kallisto-sleuth-users). There is a wealth of information already there that is easily searchable. If you don't see your question addressed already, then you can post your question to the google group. And in general, google is your friend :)

Since this is not a bug in the program, I'm going to close this issue.

**Closed by warrenmcg** 2017-07-12 19:17 UTC

**Comment by Rhinogradentia** [comment] 2017-07-13 07:05
Thanks a lot for the explanation!

Best
Nadine
