### ISSUE TITLE
sleuth_prep is insensitive to sample ordering

### ISSUE THREAD

**Issue by jmacdon** [pachterlab/sleuth#39] opened 2015-10-23 18:58 UTC
I posted this on the google groups site, but am re-posting here, as it is a bug report. Here is the example I posted there:

> cbind(kal_dirs, s2c)
                kal_dirs                sample treatment
1   ../data/A8890_quant   ../data/A8890_quant       :DE
2 ../data/A8898.1_quant ../data/A8898.1_quant       :FA
3 ../data/A8898.2_quant ../data/A8898.2_quant       :FA
4   ../data/A8965_quant   ../data/A8965_quant       :DE
5 ../data/A8969.1_quant ../data/A8969.1_quant       :FA
6 ../data/A8969.2_quant ../data/A8969.2_quant       :FA
8 ../data/A9068.2_quant ../data/A9068.2_quant       :DE
9 ../data/A9068.3_quant ../data/A9068.3_quant       :DE
> z <- sleuth_prep(kal_dirs, s2c, as.formula(model))
reading in kallisto results
........
normalizing est_counts
23501 targets passed the filter
normalizing tpm
merging in metadata
normalizing bootstrap samples
> ind <- sample(1:8,8)
> ind
[1] 1 4 3 7 5 2 8 6
> kal_dirs2 <- kal_dirs[ind]
> s2c2 <- s2c[ind,]
> cbind(kal_dirs2, s2c2)
               kal_dirs2                sample treatment
1   ../data/A8890_quant   ../data/A8890_quant       :DE
4   ../data/A8965_quant   ../data/A8965_quant       :DE
3 ../data/A8898.2_quant ../data/A8898.2_quant       :FA
8 ../data/A9068.2_quant ../data/A9068.2_quant       :DE
5 ../data/A8969.1_quant ../data/A8969.1_quant       :FA
2 ../data/A8898.1_quant ../data/A8898.1_quant       :FA
9 ../data/A9068.3_quant ../data/A9068.3_quant       :DE
6 ../data/A8969.2_quant ../data/A8969.2_quant       :FA
> zz <- sleuth_prep(kal_dirs2, s2c2, as.formula(model))
reading in kallisto results
........
normalizing est_counts
23501 targets passed the filter
normalizing tpm
merging in metadata
normalizing bootstrap samples

So I have read in the data in different orders, no?

> head(sleuth:::obs_to_matrix(z, "est_counts"))
             ../data/A8890_quant ../data/A8898.1_quant ../data/A8898.2_quant
NM_001001130          175.556951            141.077300             152.44582
NM_001001144         1966.587345           1422.623669            1185.27356
NM_001001152           66.189525             53.597640              53.12641
NM_001001160            0.000000              0.000000               0.00000
NM_001001176            0.000000            187.898109             308.09206
NM_001001177            2.126351              8.508835              11.27110
             ../data/A8965_quant ../data/A8969.1_quant ../data/A8969.2_quant
NM_001001130           176.43989             159.70493            150.430519
NM_001001144          1174.68547             851.07965           1005.135955
NM_001001152            52.31462              80.26544             56.711192
NM_001001160             0.00000               0.00000              0.000000
NM_001001176           354.61184             413.44441            156.771035
NM_001001177            10.65362               0.00000              2.082765
             ../data/A9068.2_quant ../data/A9068.3_quant
NM_001001130             152.85070            136.780545
NM_001001144            1625.05227           1246.889812
NM_001001152              51.27763             28.818195
NM_001001160               0.00000              0.000000
NM_001001176             144.19206              0.000000
NM_001001177               5.05182              8.507397
> head(sleuth:::obs_to_matrix(zz, "est_counts"))
             ../data/A8890_quant ../data/A8898.1_quant ../data/A8898.2_quant
NM_001001130          175.556951            141.077300             152.44582
NM_001001144         1966.587345           1422.623669            1185.27356
NM_001001152           66.189525             53.597640              53.12641
NM_001001160            0.000000              0.000000               0.00000
NM_001001176            0.000000            187.898109             308.09206
NM_001001177            2.126351              8.508835              11.27110
             ../data/A8965_quant ../data/A8969.1_quant ../data/A8969.2_quant
NM_001001130           176.43989             159.70493            150.430519
NM_001001144          1174.68547             851.07965           1005.135955
NM_001001152            52.31462              80.26544             56.711192
NM_001001160             0.00000               0.00000              0.000000
NM_001001176           354.61184             413.44441            156.771035
NM_001001177            10.65362               0.00000              2.082765
             ../data/A9068.2_quant ../data/A9068.3_quant
NM_001001130             152.85070            136.780545
NM_001001144            1625.05227           1246.889812
NM_001001152              51.27763             28.818195
NM_001001160               0.00000              0.000000
NM_001001176             144.19206              0.000000
NM_001001177               5.05182              8.507397

No I have not - the samples when extracted for model fitting, etc, are in alpha-numerical order. But what about the design matrices that will be used to fit the models?

> z$design_matrix
  (Intercept) treatment:DE
1           1            1
2           1            0
3           1            0
4           1            1
5           1            0
6           1            0
8           1            1
9           1            1
attr(,"assign")
[1] 0 1
attr(,"contrasts")
attr(,"contrasts")$treatment
[1] "contr.treatment"

> zz$design_matrix
  (Intercept) treatment:DE
1           1            1
4           1            1
3           1            0
8           1            1
5           1            0
2           1            0
9           1            1
6           1            0
attr(,"assign")
[1] 0 1
attr(,"contrasts")
attr(,"contrasts")$treatment
[1] "contr.treatment"

The design matrix for my 'zz' object does NOT reflect the underlying data! Unless you ensure that you order your kal_dirs and s2c matrices in alpha-numerical order, you will not get correct results.

**Comment by pimentel** [comment] 2015-10-23 22:01
Thanks for the detailed bug report. The design matrix is correct, but as you noted, there was a bug in `obs_to_matrix` that didn't reorder the columns. This wasn't manifesting in our test because even with the permuted columns, it just so happened that the results were still correct. I have added a regression to fix this in the future.

Anyway, the bug has been fixed in the development code and will be released along with several new features early next week.

**Closed by pimentel** 2015-10-23 22:01 UTC
Labels: bug
